geo/source/Web/Publishing/PublishingService/Controllers/HomeController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace PublishingService.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [ValidateInput(false)]
        public ActionResult Publish(string author, string description, string version, byte[] depictionStory)
        {
            var story = new DepictionStory();
            using (var db = new PublishingServiceContext())
            {
                story.Author = author;
                story.Description = description;
                story.StoryFile = depictionStory;
                story.Version = version;
                story.RandomizedURL = GenerateRandomURL(6);
                db.DepictionStories.Add(story);
                try
                {
                    db.SaveChanges();
                }
                catch (Exception e)
                {

                }
            }
            return new JsonResult { Data = string.Format("http://{0}/Home/Depiction/{1}", Request.Url.Authority, story.RandomizedURL), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        private string GenerateRandomURL(int length)
        {
            
            StringBuilder sb = new StringBuilder();
            Random random = new Random();
            string url = "";
            bool completed = false;
            while (!completed)
            {
                sb.Clear();
                for (int i = 0; i < length; i++)
                {
                    int next = random.Next(10 + 26 + 26);
                    if (next < 10)
                        sb.Append(next);
                    else if (next < 36)
                        sb.Append(Char.ConvertFromUtf32(next + 65 - 10));
                    else
                    {
                        sb.Append(Char.ConvertFromUtf32(next + 97 - 36));
                    }
                }
                url = sb.ToString();
                using (var db = new PublishingServiceContext())
                {
                    DepictionStory story = db.DepictionStories.FirstOrDefault(t => t.RandomizedURL == url);
                    completed = (story == null);
                }
            }
            return url;
        }

        public ActionResult Depiction(string id)
        {
            using (var db = new PublishingServiceContext())
            {
                DepictionStory story = db.DepictionStories.First(t => t.RandomizedURL.Equals(id));
                return View("Depiction", story);
            }
        }

        public ActionResult DepictionZIP(string id)
        {
            using (var db = new PublishingServiceContext())
            {
                DepictionStory story = db.DepictionStories.First(t => t.RandomizedURL == id);
                return new FileContentResult(story.StoryFile, System.Net.Mime.MediaTypeNames.Application.Octet);
            }
        }




    }
}

geo/source/Web/Publishing/PublishingService/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace PublishingService.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

geo/source/Web/Publishing/PublishingService/Controllers/ViewerController.cs
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PublishingService.Controllers
{
    public class ViewerController : Controller
    {

        public ActionResult Get(string version)
        {
            using (var db = new PublishingServiceContext())
            {

                DepictionViewer viewer = db.DepictionViewers.First(t => t.Version == version && !t.Deleted);
                return new FileContentResult(viewer.ViewerXAP, "System.Net.Mime.MediaTypeNames.Application.Octet");
            }
        }

        public ActionResult Upload()
        {
            return View("Upload");
        }
        public ActionResult DoUpload(string version, HttpPostedFileBase file)
        {
            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {
                // extract only the filename
                var fileName = Path.GetFileName(file.FileName);

                using (var db = new PublishingServiceContext())
                {

                    DepictionViewer viewer = db.DepictionViewers.FirstOrDefault(t => t.Version == version && !t.Deleted);
                    if (viewer != null)
                        return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "This version of the viewer already exists.  To replace it, delete it first, then upload.");

                    viewer = new DepictionViewer();
                    viewer.Version = version;
                    var memoryStream = new MemoryStream();
                    file.InputStream.CopyTo(memoryStream);
                    viewer.ViewerXAP = memoryStream.ToArray();
                    db.DepictionViewers.Add(viewer);
                    db.SaveChanges();
                    return new ContentResult { Content = string.Format("Successfully uploaded version {0}", version) };
                }


                //// store the file inside ~/App_Data/uploads folder
                //var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                //file.SaveAs(path);
            }
            // redirect back to the index action to show the form once again
            //return RedirectToAction("Index");
            return null;
        }
        //{
        //    using (var db = new PublishingServiceContext())
        //    {

        //        DepictionViewer viewer = db.DepictionViewers.First(t => t.Version == version && !t.Deleted);
        //        if (viewer != null)
        //            return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "This version of the viewer already exists.  To replace it, delete it first, then upload.");

        //        viewer = new DepictionViewer();
        //        viewer.Version = version;
        //        viewer.ViewerXAP = viewerXAP;
        //        db.DepictionViewers.Add(viewer);
        //        db.SaveChanges();
        //        return new ContentResult { Content = string.Format("Successfully uploaded version {0}",version) };
        //    }
        //}

        public ActionResult Delete(string version)
        {
            using (var db = new PublishingServiceContext())
            {

                DepictionViewer viewer = db.DepictionViewers.First(t => t.Version == version && !t.Deleted);
                viewer.Deleted = true;
                try
                {
                    db.SaveChanges();
                    return new ContentResult { Content = string.Format("Successfully deleted version {0}", version) };
                }
                catch (Exception e)
                {
                    return new ContentResult { Content = string.Format("Failed to delete version {0}", version) };
                }
            }
        }
    }
}

geo/source/Web/Publishing/PublishingService/Views/Home/Depiction.cshtml
@model PublishingService.DepictionStory

@{
    Layout = null;
    
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <!-- saved from url=(0014)about:internet -->
<style type="text/css"> 
html, body { overflow:auto } 
</style>
<head>
    <title>DepictionSilverlight</title>
    <script type="text/javascript" src="..\..\scripts\Silverlight.js"></script>

    <script type="text/javascript">
        function onSilverlightError(sender, args) {

            var appSource = "";
            if (sender != null && sender != 0) {
                appSource = sender.getHost().Source;
            }
            var errorType = args.ErrorType;
            var iErrorCode = args.ErrorCode;

            var errMsg = "Unhandled Error in Silverlight Application " + appSource + "\n";

            errMsg += "Code: " + iErrorCode + "    \n";
            errMsg += "Category: " + errorType + "       \n";
            errMsg += "Message: " + args.ErrorMessage + "     \n";

            if (errorType == "ParserError") {
                errMsg += "File: " + args.xamlFile + "     \n";
                errMsg += "Line: " + args.lineNumber + "     \n";
                errMsg += "Position: " + args.charPosition + "     \n";
            }
            else if (errorType == "RuntimeError") {
                if (args.lineNumber != 0) {
                    errMsg += "Line: " + args.lineNumber + "     \n";
                    errMsg += "Position: " + args.charPosition + "     \n";
                }
                errMsg += "MethodName: " + args.methodName + "     \n";
            }

            throw new Error(errMsg);
        }
    </script>

</head>
<body style="margin:0;" scroll="no">
    <div id="silverlightControlHost" style="position: fixed; height: 100%; width: 100%">
        <object data="data:application/x-silverlight-2," type="application/x-silverlight-2"
            Width="100%" Height="100%">
            <param name="source" value="http://@Request.Url.Authority/Viewer/Get?version=@Model.Version" />
            <param name="onerror" value="onSilverlightError" />
            <param name="background" value="white" />
            <param name="minRuntimeVersion" value="5.0.61118.0" />
            <param name="autoUpgrade" value="true" />
            <param name="initParams" value="depictionXMLURI=http://@Request.Url.Authority/Home/DepictionZIP/@Model.RandomizedURL"/>
			<a href="http://go.microsoft.com/fwlink/?LinkID=149156&v=5.0.61118.0" style="text-decoration:none">
				<img src="http://go.microsoft.com/fwlink/?LinkId=161376" alt="Get Microsoft Silverlight" style="border-style:none"/>
			</a>
        </object>
    </div>
</body>
</html>

geo/source/Web/Publishing/PublishingService/Views/Home/Index.cshtml
<header>
    <div class="content-wrapper">
        <div class="float-left">
            <p class="site-title">
                <a href="~/">ASP.NET Web API</a></p>
        </div>
    </div>
</header>
<div id="body">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Welcome to ASP.NET Web API!</h1>
                <h2>Modify the code in this template to jump-start your ASP.NET Web API development.</h2>
            </hgroup>
            <p>
                ASP.NET Web API allows you to expose your applications, data and services to the
                web directly over HTTP.
            </p>
            <p>
                To learn more about ASP.NET Web API visit
                <a href="http://go.microsoft.com/fwlink/?LinkID=238195" title="ASP.NET Web API Website">http://asp.net/web-api</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET Web API.
                If you have any questions about ASP.NET Web API, visit
                <a href="http://go.microsoft.com/fwlink/?LinkID=238196" title="ASP.NET Web API Forum">our forums</a>.
            </p>
        </div>
    </section>
    <section class="content-wrapper main-content clear-fix">
        <h3>We suggest the following steps:</h3>
        <ol class="round">
            <li class="one">
                <h5>Getting Started</h5>
                ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
                a broad range of clients, including browsers and mobile devices. ASP.NET Web API
                is an ideal platform for building RESTful applications on the .NET Framework.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245160">Learn more…</a>
            </li>

            <li class="two">
                <h5>Add NuGet packages and jump-start your coding</h5>
                NuGet makes it easy to install and update free libraries and tools.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245161">Learn more…</a>
            </li>
            <li class="three">
                <h5>Find Web Hosting</h5>
                You can easily find a web hosting company that offers the right mix of features
                and price for your applications.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245164">Learn more…</a>
            </li>
        </ol>
    </section>
</div>

geo/source/Web/Publishing/PublishingService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

geo/source/Web/Publishing/PublishingService/Views/Viewer/Upload.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Upload Depiction Viewer</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("DoUpload", "Viewer", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" />
            <input type="text" name="version"/>
            <input type="submit" value="OK" />
        }
    </div>
</body>
</html>